[theme]

# Primary accent for interactive elements
primaryColor = '#6C441D'  # Orange

# Background color for the main content area
backgroundColor = '#121212'  # Dark gray background

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#212121'  # Slightly lighter gray background

# Color used for almost all text
textColor = '#FFFFFF'  # White text

# Font family for all text in the app, except code blocks
font = "sans serif"
